
server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/wedding_planner
    username: wedding
    password: wedding
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    baseline-on-migrate: true
